### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by ScubaSteve1616** [THEREALWWEFAN231/Inertia#686]
**Inertia Utility Mod version:** 
3.1.2-1.12.2
**Minecraft version:** 
1.12.2
**Operating system:** 
Windows
**Optifine/Other mods:** 
journeymap- 1.12.2-5.7.1
KAMI-Blue-v1.1.6-release
LunatriusCore-1.12.2-1.2.0.42-universal
moreoverlays-1.15.1-mc1.12.2
Schematica-1.12.2-1.8.0.169-universal
OptiFine_1.12.2_HD_U_F5
**What's the issue:** 
once all the mods are done loading through forge the game opens in a black screen
**Crash-report(Would be very useful also please format):**

**Comment by R281** [comment]
lol was aboutta post my bug report on this too xD

**Comment by R281** [comment]
![bug-report](https://user-images.githubusercontent.com/42677102/90694477-5997ca80-e281-11ea-9e80-d7ae7ed59bcb.png)

**Comment by R281** [comment]
(btw, removing all of the forge and inertia related stuff doesnt work anymore, the game still goes black even in 3.1.2)

**Comment by THEREALWWEFAN231** [comment]
I am aware of this, I know where the problem is, but no idea why its happening, it only happens for some people only on the 1.12.2 forge version.

**Comment by R281** [comment]
" I know where the problem is, " 
cool, is it like a  bug with assets in the client or something?

**Comment by 8Int** [comment]
try remove Kami blue, i also some bugs like this  but after removing Kami blue some issues were fixed

**Comment by Lopsidedchez** [comment]
This happened to me too

**Comment by ScubaSteve1616** [comment]
Still having this issue. not sure if you've looked at it yet

**Comment by gozzy2** [comment]
**same idk why**

> before all was ok  now i reinstalled inertia 1.12.2 and same black screen

**Comment by Paralusion** [comment]
duplicate of #618
